FROM clojure:%%TAG%%
MAINTAINER Christopher Shea <chris@democracy.works>

ADD libyjpagent.so /yourkit/libyjpagent.so
ADD license-redist.txt /yourkit/license-redist.txt

ENV YOURKIT_AGENT_OPTION -agentpath:/yourkit/libyjpagent.so=port=10000

EXPOSE 10000
